### ISSUE TITLE
Missing or incompatible modules in URobotSim plugin

### ISSUE THREAD

**Issue by TheRobotStudio** [robcog-iai/URoboSim-depr#15]
Hello,

I'm using the Unreal Editor 4.16 on Ubuntu 16.04.
I've create a new project, with a "Plugins" directory inside which I've copied the whole URoboSim folder.
When I try to open the project I have the following error in a pop-up window : 
Missing or incompatible modules in URoboSim plugin - would you like to disable it ? ...

Do you know how to solve that issue ?

Thanks !

**Comment by andreihaidu** [comment]
Hi, yes, try using the latest unreal engine, at the moment 4.18.

**Comment by TheRobotStudio** [comment]
Hi,

Thanks for your reply, I now have EU4.18 working, but now it says that the binaries for URoboSim are missing. How do you build them under linux ?

Best!

**Comment by andreihaidu** [comment]
Hi,

can you remove the binary and the intermediate folders from your plugin and project, and try again. That might be the issue with the error msg.

Cheers!

**Comment by TheRobotStudio** [comment]
It was the intermediate folder in the project that caused problem.
Now I can launch a project and see the URoboSim plugin in the plugin settings window.
But as I haven't build the binaries for it yet, it fails when I activate it.
It gives the same error as before : Binaries for the 'URoboSim' plugin are missing...

How do you actually build the binaries ? From the UE ? 

Cheers!

**Comment by TheRobotStudio** [comment]
I could do it from a C++ project, now it works, thanks :) !
Cheers!
